/**
 * Dungeon dossiers and the briefing given when a Triforce shard is claimed.
 *
 * Taking the shard in level N shows, in order:
 *   1. `LEVELS[N].onPiece`   — what that shard means for the story
 *   2. `LEVELS[N + 1].brief` — where the next labyrinth is and what waits there
 *   3. warnings, built from what the player actually left behind on the floor
 *
 * `LEVELS[N].onEnter` is separate: it plays the first time Link stands inside
 * that labyrinth, once per save, and describes the place he is standing in
 * rather than the place he is going.
 *
 * Keeping `brief` on the labyrinth it describes means each dungeon's write-up
 * lives in exactly one place. `entrance.screen` is checked against the
 * extracted overworld tables by `npm test`, so a wrong screen id cannot ship.
 *
 * See ./README.md for the entry shape and the charset rules.
 */

/** @type {Array<object>} indexed by level number (index 0 unused). */
export const LEVELS = [
  null,

  // --- 1 ---------------------------------------------------------------------
  {
    level: 1,
    name: 'THE EAGLE',
    guardian: 'AQUAMENTUS',
    treasure: 'THE BOW',
    entrance: { screen: 0x37, how: 'open' },
    brief: [
      'THE FIRST LABYRINTH IS NORTH OF THE CAVE WHERE YOU WOKE, IN THE HIGH GROUND EAST OF THE LAKE. ITS MOUTH STANDS OPEN.',
      'THE EAGLE IS SHALLOW AND HONEST. A ONE HORNED THING CALLED AQUAMENTUS HOLDS THE SHARD. IT SPITS IN THREES.',
      'THE BOW IS IN THERE. TAKE IT EVEN IF YOU HAVE NO ARROWS YET. LATER DOORS DO NOT OPEN WITHOUT IT.',
    ],
    onEnter: [
      'LABYRINTH 1. THE EAGLE. THE AIR CHANGES ON THE FIRST STAIR AND KEEPS CHANGING ALL THE WAY DOWN.',
      'THIS PLACE IS SHALLOW AND IT DOUBLES BACK ON ITSELF ONCE. IT WAS BUILT TO BE SURVIVED, WHICH IS NOT TRUE OF THE OTHER SEVEN.',
      'FIND THE MAP AND THE COMPASS BEFORE THE SHARD. LEARN THE HABIT HERE, WHERE IT IS CHEAP TO LEARN.',
    ],
    onPiece: [
      'THE SHARD IS WARM IN YOUR HAND. 1 OF 8. SOMEWHERE UNDER DEATH MOUNTAIN, ZELDA FEELS IT COME BACK.',
      'GANON WILL FEEL IT TOO. THE ROADS WILL BE WORSE FROM HERE, AND THE THINGS ON THEM WILL BE LOOKING FOR YOU BY NAME.',
      'YOUR HEART IS STRONGER THAN IT WAS. THE OLD MAN IN THE CAVE ABOVE THE LAKE WILL TRADE A WHITE BLADE FOR 5 HEART CONTAINERS.',
      'AND IF YOU CARRIED THE BOW OUT OF HERE, FIND A MERCHANT AND BUY ARROWS FOR IT. A BOW ON ITS OWN IS A WALKING STICK.',
    ],
    marks: [{ caveId: 0x12, clears: 'whiteSword', label: 'WHITE SWORD' }],
  },

  // --- 2 ---------------------------------------------------------------------
  {
    level: 2,
    name: 'THE MOON',
    guardian: 'DODONGO',
    treasure: 'THE MAGICAL BOOMERANG',
    entrance: { screen: 0x3c, how: 'open' },
    brief: [
      'THE SECOND LABYRINTH IS EAST AND A LITTLE NORTH, WHERE THE MOUNTAINS COME DOWN TO MEET THE ROAD. THE WAY IN IS OPEN.',
      'THE MOON IS NARROW AND IT DOUBLES BACK. DODONGO GUARDS THE SHARD. IT EATS ANYTHING, SO FEED IT SMOKE. BOMBS, THEN THE BLADE.',
      'BRING BOMBS FOR THE WALLS AS WELL. THE MAGICAL BOOMERANG IS INSIDE, AND IT COMES BACK FROM ANY DISTANCE.',
    ],
    onEnter: [
      'LABYRINTH 2. THE MOON. A LONG THIN THING THAT FOLDS BACK ON ITSELF, AND HALF OF IT IS BEHIND WALLS THAT LOOK SOLID.',
      'CARRY BOMBS OR CARRY NOTHING. WHEN A CORRIDOR ENDS FOR NO REASON, THE REASON IS THAT SOMEBODY BRICKED IT UP.',
      'DODONGO LIVES AT THE BOTTOM. IT SWALLOWS WHATEVER IT MEETS, SO GIVE IT SOMETHING WORTH SWALLOWING.',
    ],
    onPiece: [
      '2 OF 8. THE SHARDS PULL AT EACH OTHER NOW, FAINTLY, LIKE TWO LODESTONES IN A POCKET.',
      'IMPA SAID THE PRINCESS SPLIT THE RELIC IN ONE NIGHT AND HID EACH PIECE WHERE A DIFFERENT HORROR SLEPT. SHE CHOSE WELL.',
      'YOU HAVE ENOUGH ROAD BEHIND YOU NOW TO BE WORTH ROBBING. THE MOBLINS WHO CALL YOU IN OFF THE PATH ARE PAYING, NOT ASKING.',
      'AND SOMEWHERE ON THE SOUTH COAST AN OLD MAN WHO CANNOT WALK ANY MORE IS STILL WRITING LETTERS. ONE OF THEM IS FOR YOU.',
    ],
    marks: [{ caveId: 0x18, clears: 'letter', label: 'THE LETTER' }],
  },

  // --- 3 ---------------------------------------------------------------------
  {
    level: 3,
    name: 'THE MANJI',
    guardian: 'MANHANDLA',
    treasure: 'THE RAFT',
    entrance: { screen: 0x74, how: 'open' },
    brief: [
      'THE THIRD LABYRINTH IS SOUTH AND WEST, SUNK IN THE OPEN SAND BELOW THE LAKE. WALK THE BEACH AND YOU WILL FIND THE STAIR.',
      'MANHANDLA WAITS AT THE HEART OF IT. FOUR SNAPPING HEADS ON ONE STALK, AND IT GETS FASTER AS YOU CUT THEM OFF.',
      'THE RAFT IS IN THERE. WITHOUT IT THE FOURTH LABYRINTH CANNOT BE REACHED AT ALL, SO DO NOT LEAVE UNTIL YOU HAVE IT.',
    ],
    onEnter: [
      'LABYRINTH 3. THE MANJI. FOUR ARMS OFF ONE CROSSING, AND SAND SIFTING THROUGH THE CEILING IN EVERY ROOM.',
      'MANHANDLA SITS AT THE CENTER. FOUR SNAPPING HEADS ON ONE STALK, AND EVERY HEAD YOU CUT OFF MAKES THE REST OF IT FASTER.',
      'THE RAFT IS DOWN HERE SOMEWHERE. DO NOT WALK OUT WITHOUT IT. THE FOURTH LABYRINTH IS ON AN ISLAND AND HAS NO BRIDGE.',
    ],
    onPiece: [
      '3 OF 8. THE SAND OVER YOUR HEAD SHIFTS AS THE SHARD LEAVES ITS ROOM, AS IF THE PLACE WERE GLAD TO BE RID OF IT.',
      'WITH THE RAFT YOU ARE NO LONGER STOPPED BY WATER. EVERY DOCK ON THE COAST IS A ROAD NOW, AND SOME OF THEM GO SOMEWHERE.',
      'WALK THE COAST EAST UNTIL THE LAND RUNS OUT. THERE IS A DOCK AT THE END OF IT, AND SOMETHING ON THE FAR SIDE WORTH THE CROSSING.',
      'HALFWAY. THE ROADS AHEAD ARE THE ONES GANON ACTUALLY GARRISONS. GO IN WITH FULL HEARTS OR DO NOT GO IN.',
    ],
  },

  // --- 4 ---------------------------------------------------------------------
  {
    level: 4,
    name: 'THE SNAKE',
    guardian: 'GLEEOK',
    treasure: 'THE STEPLADDER',
    entrance: { screen: 0x45, how: 'raft' },
    brief: [
      'THE FOURTH LABYRINTH SITS ON THE ISLAND IN THE MIDDLE OF THE GREAT LAKE. NO BRIDGE REACHES IT.',
      'TAKE THE RAFT FROM THE DOCK ON THE LAKE SHORE AND LET IT CARRY YOU ACROSS. THE STAIR IS WAITING ON THE FAR SIDE.',
      'A GLEEOK HOLDS THE SHARD. TWO HEADS ON LONG NECKS, AND A SEVERED HEAD KEEPS FLYING AND KEEPS BITING.',
      'THE STEPLADDER IS INSIDE. IT BRIDGES ANY SINGLE GAP OF WATER, ABOVE GROUND AND BELOW IT.',
    ],
    onEnter: [
      'LABYRINTH 4. THE SNAKE. IT COILS. THERE IS ONE WAY THROUGH AND IT PASSES THE SAME ROOMS THREE TIMES.',
      'A GLEEOK HOLDS THE SHARD. TWO HEADS ON NECKS LONGER THAN THE ROOM, AND A HEAD YOU CUT OFF KEEPS FLYING AND KEEPS BITING.',
      'THE STEPLADDER IS DOWN HERE, AND SOME OF THIS LABYRINTH IS BEHIND WATER THAT ONLY THE STEPLADDER CROSSES.',
    ],
    onPiece: [
      '4 OF 8. HALF. THE SHARD IS COLDER THAN THE LAST THREE AND IT HUMS WHEN YOU HOLD IT STILL.',
      'HALF THE TRIFORCE OF WISDOM IS IN YOUR PACK AND HALF OF IT IS STILL UNDER FOUR DIFFERENT MONSTERS. GANON KNOWS THAT COUNT TOO.',
      'THE STEPLADDER CHANGES THE MAP. STREAMS THAT TURNED YOU BACK ALL SUMMER ARE ONE STEP WIDE NOW.',
      'THERE ARE STONES STANDING ALONE ON THE MOUNTAIN ROADS THAT ARE NOT ROCKS AND NOT GRAVES. ONE OF THEM IS GUARDING A BRACELET.',
      'PUSH WHAT WILL MOVE. BURN WHAT WILL BURN. EVERY SECRET YOU LEAVE ABOVE GROUND IS A HEART YOU WILL WISH YOU HAD BELOW IT.',
    ],
  },

  // --- 5 ---------------------------------------------------------------------
  {
    level: 5,
    name: 'THE LIZARD',
    guardian: 'DIGDOGGER',
    treasure: 'THE RECORDER',
    entrance: { screen: 0x0b, how: 'open' },
    brief: [
      'THE FIFTH LABYRINTH IS FAR NORTH AND EAST, ON THE HIGH GROUND ABOVE THE GRAVEYARD. THE MOUTH IS OPEN TO ANYONE WHO CLIMBS THAT FAR.',
      'DIGDOGGER IS DOWN THERE. IT CANNOT BE CUT WHILE IT IS WHOLE. IT HATES A CERTAIN KIND OF SOUND, AND SOUND IS THE ONLY KEY.',
      'THE RECORDER IS IN THE SAME LABYRINTH. TAKE IT FIRST AND THE BOSS BECOMES A FIGHT INSTEAD OF A WALL.',
    ],
    onEnter: [
      'LABYRINTH 5. THE LIZARD. THE DEEPEST THING YOU HAVE WALKED INTO SO FAR, AND THE FIRST ONE THAT IS DARK IN PLACES.',
      'CARRY A CANDLE. A ROOM YOU CANNOT SEE IS A ROOM THAT CAN SEE YOU.',
      'DIGDOGGER IS AT THE BOTTOM AND NO BLADE OPENS IT. THE THING THAT DOES IS ALSO DOWN HERE. FIND IT FIRST.',
    ],
    onPiece: [
      '5 OF 8. THE AIR IN THE ROOM GOES QUIET, THE WAY IT DOES BEFORE WEATHER.',
      'THE RECORDER IS MORE THAN A KEY. PLAY IT UNDER THE OPEN SKY AND A WHIRLWIND WILL COME AND CARRY YOU TO A LABYRINTH YOU HAVE ALREADY OPENED.',
      'PLAY IT AT STILL WATER AND THE WATER WILL LEAVE. NOT EVERY POND, BUT ONE OF THEM.',
      'THAT IS HOW THE SEVENTH DOOR OPENS, AND IT IS THE ONLY WAY IT OPENS. NO BOMB AND NO FIRE WILL DO IT.',
      'THREE SHARDS LEFT AND THE LABYRINTHS STOP BEING FAIR. IF A MAN UNDER A LABYRINTH OFFERS TO WIDEN YOUR BOMB SATCHEL, PAY HIM.',
    ],
  },

  // --- 6 ---------------------------------------------------------------------
  {
    level: 6,
    name: 'THE DRAGON',
    guardian: 'GOHMA',
    treasure: 'THE MAGICAL ROD',
    entrance: { screen: 0x22, how: 'open' },
    brief: [
      'THE SIXTH LABYRINTH IS IN THE NORTH WEST, BEYOND THE WOODS THAT TURN TRAVELLERS AROUND. NORTH, WEST, SOUTH, WEST TAKES YOU THROUGH THEM.',
      'GOHMA GUARDS THE SHARD, AND GOHMA IS ONE ARMOURED EYE. NO BLADE TOUCHES IT. AN ARROW THROUGH THE OPEN EYE IS THE WHOLE FIGHT.',
      'SO CARRY THE BOW, CARRY ARROWS, AND CARRY RUPEES. EVERY ARROW YOU LOOSE COSTS ONE.',
      'THE MAGICAL ROD IS INSIDE. IT THROWS THE SAME BEAM YOUR SWORD DOES, AT ANY HEALTH.',
    ],
    onEnter: [
      'LABYRINTH 6. THE DRAGON. THE WALLS HERE ARE WET AND THE THINGS ON THEM MOVE WHEN YOU ARE NOT LOOKING AT THEM.',
      'GOHMA IS AT THE END, AND GOHMA IS ONE ARMOURED EYE ON LEGS. NO SWORD WILL EVER TOUCH IT.',
      'IF YOU CAME DOWN HERE WITHOUT A BOW AND ARROWS, THE FIGHT AT THE BOTTOM IS NOT A FIGHT. IT IS A WALL. GO BACK AND ARM YOURSELF.',
    ],
    onPiece: [
      '6 OF 8. TWO LEFT. THE WEIGHT OF THE OTHER SIX IN YOUR PACK IS NOT THE WEIGHT OF GOLD.',
      'YOU HAVE COME FAR ENOUGH FOR THE LAST BLADE. UNDER ONE OF THE HEADSTONES IN THE GRAVEYARD AN OLD MAN KEEPS THE MAGICAL SWORD.',
      'HE WILL WANT 12 HEART CONTAINERS BEFORE HE PARTS WITH IT. PUSH THE STONES UNTIL ONE OF THEM GIVES.',
      'THE MAGICAL ROD IS WORTH AS MUCH. IT THROWS A BEAM AT ANY HEALTH, AND YOU WILL SPEND THE REST OF THIS QUEST HURT.',
    ],
    marks: [{ caveId: 0x13, clears: 'magicSword', label: 'MAGICAL SWORD' }],
  },

  // --- 7 ---------------------------------------------------------------------
  {
    level: 7,
    name: 'THE DEMON',
    guardian: 'AQUAMENTUS',
    treasure: 'THE RED CANDLE',
    entrance: { screen: 0x42, how: 'recorder' },
    brief: [
      'THE SEVENTH LABYRINTH IS IN THE WEST, UNDER A ROUND POND THAT SITS BY ITSELF WITH NOTHING GROWING AT ITS EDGE.',
      'THERE ARE SECRETS WHERE FAIRIES DO NOT LIVE. STAND AT THAT WATER AND PLAY THE RECORDER. THE POND WILL DRAIN AND LEAVE A STAIR.',
      'AQUAMENTUS HOLDS THIS SHARD TOO, AND IT IS NOT THE ONE YOU BEAT IN THE EAGLE. THE HALLS AROUND IT ARE FULL OF THINGS THAT EAT LIGHT.',
      'THE RED CANDLE IS INSIDE. IT BURNS AS OFTEN AS YOU LIKE INSTEAD OF ONCE PER ROOM.',
    ],
    onEnter: [
      'LABYRINTH 7. THE DEMON. THE POND CLOSED OVER THE STAIR BEHIND YOU AND THE WALLS DOWN HERE ARE DRY AS PAPER.',
      'THIS PLACE EATS LIGHT. WHOLE ROOMS OF IT ARE BLACK, AND A BLUE CANDLE ONLY BURNS ONCE IN EACH.',
      'AN AQUAMENTUS HOLDS THIS SHARD, AND IT IS NOT THE ONE YOU KILLED IN THE EAGLE. IT HAS HAD LONGER TO GROW.',
      'THERE IS A HUNGRY THING SITTING IN A DOORWAY DOWN HERE THAT WILL NOT MOVE FOR STEEL. IT WILL MOVE FOR FOOD.',
    ],
    onPiece: [
      '7 OF 8. THE SHARDS ARE LOUD NOW. YOU CAN FEEL THEM TRYING TO CLOSE THE LAST GAP.',
      'ONE MORE AND THE TRIFORCE OF WISDOM IS WHOLE. UNTIL THEN DEATH MOUNTAIN WILL NOT LET YOU PAST ITS DOOR.',
      'THE RED CANDLE BURNS AS OFTEN AS YOU LIKE NOW. EVERY BUSH AND EVERY LONE TREE IN HYRULE IS A QUESTION YOU CAN FINALLY AFFORD TO ASK.',
      'ASK THEM. THE EIGHTH DOOR IS UNDER ONE OF THEM, AND THERE IS NO OTHER SIGN ABOVE GROUND THAT IT IS THERE AT ALL.',
      'SPEND WHAT YOU HAVE BEFORE THE LAST TWO. A MERCHANT WITH A BLUE RING, A SECOND POTION, A BIGGER SATCHEL. NONE OF IT HELPS YOU DEAD.',
    ],
  },

  // --- 8 ---------------------------------------------------------------------
  {
    level: 8,
    name: 'THE LION',
    guardian: 'GLEEOK',
    treasure: 'THE MAGICAL KEY AND THE BOOK OF MAGIC',
    entrance: { screen: 0x6d, how: 'burn' },
    brief: [
      'THE EIGHTH LABYRINTH IS SOUTH AND EAST, IN THE THIN WOOD ABOVE THE COAST. THERE IS NO DOOR THERE UNTIL YOU MAKE ONE.',
      'BURN THE TREE THAT STANDS APART FROM THE OTHERS. THE STAIR IS UNDER IT.',
      'A GLEEOK WITH FOUR HEADS HOLDS THE LAST SHARD. IT IS THE LONGEST FIGHT IN HYRULE AND IT DOES NOT PAUSE.',
      'TWO PRIZES ARE INSIDE. THE MAGICAL KEY OPENS EVERY LOCK FOREVER, AND THE BOOK OF MAGIC SETS THE ROD ALIGHT. TAKE BOTH.',
    ],
    onEnter: [
      'LABYRINTH 8. THE LION. THE BIGGEST OF THE EIGHT, AND THE ONLY ONE THAT KEEPS TWO PRIZES INSTEAD OF ONE.',
      'THE MAGICAL KEY IS HERE, AND THE BOOK OF MAGIC. LEAVE WITHOUT EITHER AND YOU WILL WALK BACK DOWN FOR IT LATER, TIRED.',
      'A GLEEOK WITH FOUR HEADS HAS THE LAST SHARD. IT IS THE LONGEST FIGHT IN HYRULE AND IT NEVER PAUSES TO LET YOU BREATHE.',
    ],
    onPiece: [
      '8 OF 8. THE SHARDS RISE OUT OF YOUR PACK ON THEIR OWN AND FIT THEMSELVES TOGETHER.',
      'THE TRIFORCE OF WISDOM IS WHOLE. IT BURNS STEADY AND GOLD AND IT POINTS NORTH, THE WAY A COMPASS POINTS.',
      'THAT IS WHAT ZELDA BOUGHT WITH HER FREEDOM. SHE BROKE A RELIC OF THE GODS RATHER THAN HAND IT OVER, AND SHE HAS PAID FOR IT EVERY DAY SINCE.',
      'NOW GO AND SPEND IT. THERE IS ONE DOOR LEFT AND IT IS THE ONLY ONE THE WHOLE RELIC WILL OPEN.',
      'THIS IS THE LAST TIME ANYONE WILL WARN YOU ABOUT ANYTHING. TAKE THE BEST BLADE, EVERY BOMB, EVERY POTION, EVERY RUPEE YOU OWN.',
    ],
  },

  // --- 9 ---------------------------------------------------------------------
  {
    level: 9,
    name: 'DEATH MOUNTAIN',
    guardian: 'GANON',
    treasure: 'THE SILVER ARROW',
    entrance: { screen: 0x05, how: 'bomb' },
    brief: [
      'THE LAST DOOR IS AT THE TOP OF DEATH MOUNTAIN, IN THE FAR NORTH. THE PATH THERE IS A MAZE OF GREY ROCK AND IT IS PATROLLED.',
      'THE WAY IN IS A WALL. FIND THE GREY ROCK FACE AND BOMB IT. THE TRIFORCE OF WISDOM WILL LET YOU THROUGH WHAT IS BEHIND IT.',
      'THE SILVER ARROW IS HIDDEN INSIDE THE MOUNTAIN. GANON CANNOT BE KILLED WITHOUT IT, SO FIND IT BEFORE YOU FIND HIM.',
      'HE FIGHTS UNSEEN. CUT AT THE PLACE WHERE THE AIR IS WRONG UNTIL HE HOLDS STILL, THEN LOOSE THE SILVER ARROW INTO HIM.',
      'CARRY THE BEST BLADE YOU OWN, EVERY BOMB YOU CAN, AND ENOUGH RUPEES TO KEEP SHOOTING. ZELDA IS BEHIND HIM.',
    ],
    onEnter: [
      'DEATH MOUNTAIN. NOTHING LIVING LAID THESE STONES AND THE TRIFORCE IN YOUR PACK IS THE ONLY REASON THE DOOR LET YOU THROUGH.',
      'THIS IS GANON\'S HOUSE. IT IS BIGGER THAN THE OTHER EIGHT PUT TOGETHER AND EVERY ROOM IN IT IS DEFENDED.',
      'THE SILVER ARROW IS HIDDEN SOMEWHERE INSIDE. FIND IT BEFORE YOU FIND HIM, BECAUSE WITHOUT IT HE CANNOT BE KILLED AT ALL.',
      'ZELDA IS HERE. SHE HAS BEEN HERE SINCE THE NIGHT SHE BROKE THE RELIC. THERE IS NOTHING LEFT TO COLLECT AFTER THIS ONE.',
    ],
    onPiece: [],
  },
];

/**
 * Warnings for treasure left on a labyrinth floor, keyed by ROM item type.
 * Anything not listed here is treated as small change and never nagged about.
 *
 * These are deliberately the terse end of the pack. Everything else here got
 * longer; the audit at the tail of a briefing did not, because it lands after
 * a dozen pages the player has already read and it is the part they did not
 * ask for. `storyText.test.js` holds each of these to a single box page — the
 * full warning tail is then five presses, not ten.
 */
export const ITEM_ADVICE = {
  /** $0A bow */
  0x0a: 'YOU LEFT THE BOW BEHIND. GOHMA AND GANON DIE TO ARROWS AND NOTHING ELSE.',
  /** $0C raft */
  0x0c: 'YOU LEFT THE RAFT BEHIND. THE ISLAND LABYRINTH CANNOT BE REACHED WITHOUT IT.',
  /** $0D stepladder */
  0x0d: 'YOU LEFT THE STEPLADDER BEHIND. WATER WILL TURN YOU BACK UNTIL YOU HAVE IT.',
  /** $05 recorder */
  0x05: 'YOU LEFT THE RECORDER BEHIND. DIGDOGGER AND THE 7TH DOOR BOTH NEED IT.',
  /** $10 magical rod */
  0x10: 'YOU LEFT THE MAGICAL ROD BEHIND. IT THROWS A BEAM AT ANY HEALTH.',
  /** $11 book of magic */
  0x11: 'YOU LEFT THE BOOK OF MAGIC BEHIND. IT SETS THE ROD ALIGHT.',
  /** $07 red candle */
  0x07: 'YOU LEFT THE RED CANDLE BEHIND. THE BLUE ONE BURNS ONCE A ROOM.',
  /** $0B magical key */
  0x0b: 'YOU LEFT THE MAGICAL KEY BEHIND. IT OPENS EVERY LOCK AND IS NEVER SPENT.',
  /** $1E magical boomerang */
  0x1e: 'YOU LEFT THE MAGICAL BOOMERANG BEHIND. IT STUNS A WHOLE ROOM ACROSS.',
  /** $1D boomerang */
  0x1d: 'YOU LEFT THE BOOMERANG BEHIND. IT STUNS WHAT YOU CANNOT REACH.',
  /** $09 silver arrow */
  0x09: 'YOU LEFT THE SILVER ARROW BEHIND. GANON CANNOT BE FINISHED WITHOUT IT.',
  /** $13 red ring */
  0x13: 'YOU LEFT THE RED RING BEHIND. IT CUTS EVERY WOUND TO A QUARTER.',
  /** $12 blue ring */
  0x12: 'YOU LEFT THE BLUE RING BEHIND. IT HALVES EVERY WOUND YOU TAKE.',
  /** $14 power bracelet */
  0x14: 'YOU LEFT THE POWER BRACELET BEHIND. THE STANDING ROCKS WILL NOT MOVE.',
  /** $1A heart container */
  0x1a: 'YOU LEFT A HEART CONTAINER ON THE FLOOR. THE SWORD OLD MEN COUNT THOSE.',
  /** $17 map */
  0x17: 'YOU NEVER FOUND THE MAP. PAPER IS CHEAPER THAN WALKING IT TWICE.',
  /** $16 compass */
  0x16: 'YOU NEVER FOUND THE COMPASS. IT POINTS STRAIGHT AT THE SHARD.',
  /** $1C magical shield */
  0x1c: 'YOU LEFT THE MAGICAL SHIELD BEHIND. IT TURNS WHAT WOOD DOES NOT.',
};

/**
 * Which misses matter most, best first. Anything absent from this list still
 * gets warned about, just after everything listed here.
 */
export const MISSED_PRIORITY = [
  0x0c, // raft — hard-gates level 4
  0x0d, // stepladder
  0x05, // recorder — hard-gates level 7 and Digdogger
  0x0a, // bow — hard-gates Gohma and Ganon
  0x09, // silver arrow
  0x0b, // magical key
  0x11, // book of magic
  0x10, // magical rod
  0x07, // red candle
  0x1e, // magical boomerang
  0x1d, // boomerang
  0x14, // power bracelet
  0x13, // red ring
  0x12, // blue ring
  0x1c, // magical shield
  0x1a, // heart container
  0x17, // map
  0x16, // compass
];

/** At most this many warnings — a briefing should not become an inventory. */
export const MISSED_MAX = 3;

/** Heading page printed before the list of missed treasure. */
export const MISSED_HEADER =
  'ONE MORE THING. YOU LEFT SOMETHING DOWN THERE.';

/** How to go back — appended after the warnings. */
export const MISSED_FOOTER =
  'THE DOOR IS STILL OPEN AND CLEARED ROOMS STAY CLEARED. GO BACK WHEN YOU CAN.';
