/**
 * Where a baker gets the 16x16 pixels for a CHR tile.
 *
 * There are two enhanced art sets now and they are produced completely
 * differently — one derived procedurally from the original tile's shape, one
 * generated by FLUX — but everything downstream only wants the same thing: the
 * 256 packed (slot, shade) bytes for a given sheet and tile index. Putting that
 * behind one interface means the screen and title bakers work with either set
 * without knowing which is loaded.
 */

import fs from 'node:fs';
import path from 'node:path';
import { EXTRACTED_DIR } from '../shared/paths.js';
import { ENHANCED_TILE_PX, enhanceTile } from './enhanceTile.js';

export const AI_DIR = path.join(EXTRACTED_DIR, 'graphics_ai');
const TILE_BYTES = ENHANCED_TILE_PX * ENHANCED_TILE_PX;

/**
 * Procedural source: shades each tile from its own geometry.
 * @param {Map<string, { kind: string, tiles: Uint8Array[] }>} banks
 */
export function proceduralTileSource(banks) {
  return {
    id: 'procedural',
    /**
     * @param {string} sheetId
     * @param {number} index tile index within the sheet
     * @param {{ seed?: number }} [opts] position seed, so a repeated ground
     *   tile does not stamp identical grain across a whole field
     */
    pixels(sheetId, index, opts = {}) {
      const bank = banks.get(sheetId);
      const slots = bank?.tiles[index];
      if (!slots) return null;
      return enhanceTile(slots, {
        sheetId,
        tileIndex: index,
        kind: bank.kind,
        seed: opts.seed,
      }).pixels;
    },
  };
}

/**
 * FLUX source: reads the planes `aiTiles.py` wrote. Position seeds are ignored
 * — the art is fixed per tile, so a repeated tile genuinely repeats.
 * @param {string} [dir]
 */
export function aiTileSource(dir = AI_DIR) {
  /** @type {Map<string, Uint8Array>} */
  const planes = new Map();
  return {
    id: 'ai',
    /**
     * @param {string} sheetId
     * @param {number} index
     */
    pixels(sheetId, index) {
      let plane = planes.get(sheetId);
      if (plane === undefined) {
        const file = path.join(dir, `${sheetId}.4bpp`);
        plane = fs.existsSync(file) ? new Uint8Array(fs.readFileSync(file)) : null;
        planes.set(sheetId, plane);
      }
      if (!plane) return null;
      const off = index * TILE_BYTES;
      if (off + TILE_BYTES > plane.length) return null;
      return plane.subarray(off, off + TILE_BYTES);
    },
  };
}

/**
 * @param {'procedural'|'ai'} mode
 * @param {Map<string, { kind: string, tiles: Uint8Array[] }>} banks
 */
export function createTileSource(mode, banks) {
  return mode === 'ai' ? aiTileSource() : proceduralTileSource(banks);
}
